"use client";

/* eslint-disable @next/next/no-img-element -- Generated art must preserve its complete source aspect ratio. */

import Link from "next/link";
import { useEffect, useState } from "react";
import type { PublicGalleryImage } from "../../api/logo/gallery/storage";

const outputLabels: Record<PublicGalleryImage["outputType"], string> = {
  logo: "Logo",
  "app-icon": "Mobile app logo",
  mascot: "Mascot",
  poster: "Poster",
  "logo-with-name": "Logo + name",
};

type GalleryPage = {
  images?: PublicGalleryImage[];
  cursor?: string | null;
  error?: string;
};

async function requestGalleryPage(cursor?: string, signal?: AbortSignal) {
  const url = cursor ? `/api/logo/gallery?cursor=${encodeURIComponent(cursor)}` : "/api/logo/gallery";
  const response = await fetch(url, { signal });
  const payload = await response.json() as GalleryPage;
  if (!response.ok) throw new Error(payload.error || "The showcase couldn’t be loaded.");
  return payload;
}

function mergeImages(current: PublicGalleryImage[], incoming: PublicGalleryImage[]) {
  const merged = new Map(current.map((image) => [image.id, image]));
  for (const image of incoming) merged.set(image.id, image);
  return [...merged.values()];
}

function LogoCard({ image }: { image: PublicGalleryImage }) {
  const [unavailable, setUnavailable] = useState(false);

  return (
    <article className="logo-gallery-card">
      <a
        className="logo-gallery-art"
        href={image.imageUrl}
        target="_blank"
        rel="noreferrer"
        aria-label={`Open ${image.appName} ${outputLabels[image.outputType]} full size`}
      >
        {unavailable ? (
          <span className="logo-gallery-unavailable"><b>◇</b>Preview unavailable</span>
        ) : (
          <img
            src={image.imageUrl}
            alt={`${image.appName} ${outputLabels[image.outputType]}`}
            loading="lazy"
            decoding="async"
            onError={() => setUnavailable(true)}
          />
        )}
      </a>
    </article>
  );
}

export function LogoGallery() {
  const [images, setImages] = useState<PublicGalleryImage[]>([]);
  const [cursor, setCursor] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [hasLoaded, setHasLoaded] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    const controller = new AbortController();
    void requestGalleryPage(undefined, controller.signal)
      .then((page) => {
        setImages(page.images ?? []);
        setCursor(page.cursor ?? null);
        setError("");
      })
      .catch((reason) => {
        if (reason instanceof Error && reason.name === "AbortError") return;
        setError(reason instanceof Error ? reason.message : "The showcase couldn’t be loaded.");
      })
      .finally(() => {
        if (!controller.signal.aborted) {
          setIsLoading(false);
          setHasLoaded(true);
        }
      });
    return () => controller.abort();
  }, []);

  async function loadMore() {
    if (!cursor || isLoading) return;
    setIsLoading(true);
    setError("");
    try {
      const page = await requestGalleryPage(cursor);
      setImages((current) => mergeImages(current, page.images ?? []));
      setCursor(page.cursor ?? null);
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : "More images couldn’t be loaded.");
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <main className="logo-maker-page logo-gallery-page">
      <header className="topbar logo-topbar">
        <Link href="/" className="brand" aria-label="unslop.site home">
          <span className="brand-mark">u.</span>
          <span>unslop.site</span>
        </Link>
        <nav className="site-nav" aria-label="Primary navigation">
          <Link href="/">Gallery</Link>
          <Link href="/logo" className="active">Logo Maker</Link>
        </nav>
        <p className="topbar-context">Community showcase</p>
      </header>

      <section className="logo-gallery-intro">
        <div>
          <p className="section-label">Logo maker / generated by users</p>
          <h1>Logo showcase.</h1>
          <p>A shared wall of identities generated by unslop.site visitors, newest first.</p>
        </div>
        <div className="logo-gallery-summary">
          <span><strong>{images.length}</strong>{images.length === 1 ? " image shown" : " images shown"}</span>
          <Link href="/logo">Create yours <b aria-hidden="true">↗</b></Link>
        </div>
      </section>

      <section className="logo-gallery-library" aria-label="Community logo generations">
        {error ? <p className="logo-gallery-error" role="alert">{error}</p> : null}
        {images.length ? (
          <>
            <div className="logo-gallery-grid">
              {images.map((image) => <LogoCard key={image.id} image={image} />)}
            </div>
            {cursor ? (
              <button className="logo-gallery-more" type="button" onClick={() => void loadMore()} disabled={isLoading}>
                {isLoading ? "Loading more…" : "Load more generations"}
              </button>
            ) : null}
          </>
        ) : isLoading ? (
          <div className="logo-gallery-loading"><span aria-hidden="true">◇</span><strong>Loading the showcase…</strong></div>
        ) : hasLoaded && !error ? (
          <div className="logo-gallery-empty">
            <span aria-hidden="true">◇</span>
            <h2>No shared logos yet</h2>
            <p>New visitor generations will collect here automatically.</p>
            <Link href="/logo">Create the first one <b aria-hidden="true">↗</b></Link>
          </div>
        ) : null}
      </section>
    </main>
  );
}
