"use client";

/* eslint-disable @next/next/no-img-element -- Generated art must preserve its complete source aspect ratio. */

import Link from "next/link";
import { useEffect, useState } from "react";
import { CarbonAd } from "../../carbon-ad";
import type { PublicGalleryImage } from "../../api/logo/gallery/storage";

const outputLabels: Record<PublicGalleryImage["outputType"], string> = {
  logo: "Logo",
  "app-icon": "Mobile app logo",
  mascot: "Mascot",
  poster: "Poster",
  "logo-with-name": "Logo + name",
};

type GalleryPage = {
  images?: PublicGalleryImage[];
  page?: number;
  pageCount?: number;
  total?: number;
  error?: string;
};

async function requestGalleryPage(page: number, signal?: AbortSignal) {
  const url = `/api/logo/gallery?page=${page}`;
  const response = await fetch(url, { signal });
  const payload = await response.json() as GalleryPage;
  if (!response.ok) throw new Error(payload.error || "The showcase couldn’t be loaded.");
  return payload;
}

function galleryPageHref(page: number) {
  return `/logo/gallery?page=${page}`;
}

function paginationItems(currentPage: number, pageCount: number) {
  const visiblePages = new Set([1, pageCount]);
  for (let page = currentPage - 2; page <= currentPage + 2; page += 1) {
    if (page > 1 && page < pageCount) visiblePages.add(page);
  }

  const pages = [...visiblePages].sort((left, right) => left - right);
  const items: Array<number | string> = [];
  pages.forEach((page, index) => {
    const previousPage = pages[index - 1];
    if (previousPage && page - previousPage > 1) items.push(`ellipsis-${previousPage}`);
    items.push(page);
  });
  return items;
}

function LogoCard({ image }: { image: PublicGalleryImage }) {
  const [unavailable, setUnavailable] = useState(false);
  const [previewUrl, setPreviewUrl] = useState(image.thumbnailUrl);

  return (
    <article className="logo-gallery-card">
      <a
        className="logo-gallery-art"
        href={image.imageUrl}
        target="_blank"
        rel="noreferrer"
        aria-label={`Open ${image.appName} ${outputLabels[image.outputType]} full size`}
      >
        {unavailable ? (
          <span className="logo-gallery-unavailable"><b>◇</b>Preview unavailable</span>
        ) : (
          <img
            src={previewUrl}
            alt={`${image.appName} ${outputLabels[image.outputType]}`}
            loading="lazy"
            decoding="async"
            onError={() => {
              if (previewUrl !== image.imageUrl) {
                setPreviewUrl(image.imageUrl);
                return;
              }
              setUnavailable(true);
            }}
          />
        )}
      </a>
    </article>
  );
}

export function LogoGallery({ initialPage }: { initialPage: number }) {
  const [images, setImages] = useState<PublicGalleryImage[]>([]);
  const [currentPage, setCurrentPage] = useState(initialPage);
  const [pageCount, setPageCount] = useState(1);
  const [total, setTotal] = useState(0);
  const [isLoading, setIsLoading] = useState(true);
  const [hasLoaded, setHasLoaded] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    const controller = new AbortController();
    void requestGalleryPage(initialPage, controller.signal)
      .then((page) => {
        setImages(page.images ?? []);
        setCurrentPage(page.page ?? initialPage);
        setPageCount(page.pageCount ?? 1);
        setTotal(page.total ?? page.images?.length ?? 0);
        setError("");
      })
      .catch((reason) => {
        if (reason instanceof Error && reason.name === "AbortError") return;
        setError(reason instanceof Error ? reason.message : "The showcase couldn’t be loaded.");
      })
      .finally(() => {
        if (!controller.signal.aborted) {
          setIsLoading(false);
          setHasLoaded(true);
        }
      });
    return () => controller.abort();
  }, [initialPage]);

  return (
    <main className="logo-maker-page logo-gallery-page">
      <header className="topbar logo-topbar">
        <Link href="/" className="brand" aria-label="unslop.site home">
          <span className="brand-mark">u.</span>
          <span>unslop.site</span>
        </Link>
        <nav className="site-nav" aria-label="Primary navigation">
          <Link href="/">Gallery</Link>
          <Link href="/logo">Logo Maker</Link>
          <Link href="/logo/gallery" className="active" aria-current="page">Logo Gallery</Link>
        </nav>
        <p className="topbar-context">Community showcase</p>
      </header>

      <section className="logo-gallery-intro">
        <div>
          <p className="section-label">Logo maker / generated by users</p>
          <h1>Logo showcase.</h1>
          <p>A shared wall of identities generated by unslop.site visitors, newest first.</p>
        </div>
        <div className="logo-gallery-summary">
          <span><strong>{total || images.length}</strong> generations · Page {currentPage} of {pageCount}</span>
          <Link href="/logo">Create yours <b aria-hidden="true">↗</b></Link>
        </div>
      </section>

      <CarbonAd placement="logo-gallery-top" className="carbon-slot-logo-gallery" />

      <section className="logo-gallery-library" aria-label="Community logo generations">
        {error ? <p className="logo-gallery-error" role="alert">{error}</p> : null}
        {images.length ? (
          <>
            <div className="logo-gallery-grid">
              {images.map((image) => <LogoCard key={image.id} image={image} />)}
            </div>
            {pageCount > 1 ? (
              <nav className="logo-gallery-pagination" aria-label="Logo gallery pages">
                <div className="logo-gallery-page-numbers">
                  {paginationItems(currentPage, pageCount).map((item) => typeof item === "number" ? (
                    <Link
                      key={item}
                      className="logo-gallery-page-number"
                      href={galleryPageHref(item)}
                      aria-current={item === currentPage ? "page" : undefined}
                    >
                      {item}
                    </Link>
                  ) : (
                    <span key={item} className="logo-gallery-page-ellipsis" aria-hidden="true">…</span>
                  ))}
                </div>
                <div className="logo-gallery-page-actions">
                  {currentPage > 1 ? (
                    <Link className="logo-gallery-page-action" href={galleryPageHref(currentPage - 1)} rel="prev">
                      <b aria-hidden="true">←</b>
                      <span><small>Previous</small><strong>Page {currentPage - 1}</strong></span>
                    </Link>
                  ) : (
                    <span className="logo-gallery-page-action is-disabled" aria-disabled="true">
                      <b aria-hidden="true">←</b>
                      <span><small>Previous</small><strong>First page</strong></span>
                    </span>
                  )}
                  {currentPage < pageCount ? (
                    <Link className="logo-gallery-page-action is-next" href={galleryPageHref(currentPage + 1)} rel="next">
                      <span><small>Next</small><strong>Page {currentPage + 1}</strong></span>
                      <b aria-hidden="true">→</b>
                    </Link>
                  ) : (
                    <span className="logo-gallery-page-action is-next is-disabled" aria-disabled="true">
                      <span><small>Next</small><strong>Last page</strong></span>
                      <b aria-hidden="true">→</b>
                    </span>
                  )}
                </div>
              </nav>
            ) : null}
          </>
        ) : isLoading ? (
          <div className="logo-gallery-loading"><span aria-hidden="true">◇</span><strong>Loading the showcase…</strong></div>
        ) : hasLoaded && !error ? (
          <div className="logo-gallery-empty">
            <span aria-hidden="true">◇</span>
            <h2>No shared logos yet</h2>
            <p>New visitor generations will collect here automatically.</p>
            <Link href="/logo">Create the first one <b aria-hidden="true">↗</b></Link>
          </div>
        ) : null}
      </section>
    </main>
  );
}
