import type { Metadata } from "next";
import { LogoGallery } from "./logo-gallery";

export const metadata: Metadata = {
  title: { absolute: "Generated Logo Showcase — unslop.site" },
  description: "Browse logos, mascots, app icons, and brand directions generated by unslop.site visitors.",
  robots: { index: false, follow: false },
};

type LogoGalleryPageProps = {
  searchParams: Promise<{ page?: string | string[] }>;
};

export default async function LogoGalleryPage({ searchParams }: LogoGalleryPageProps) {
  const value = (await searchParams).page;
  const rawPage = Array.isArray(value) ? value[0] : value;
  const page = rawPage && /^[1-9]\d{0,5}$/.test(rawPage) ? Number(rawPage) : 1;
  return <LogoGallery key={page} initialPage={page} />;
}
