import type { Metadata } from "next";
import { LogoGallery } from "./logo-gallery";

export const metadata: Metadata = {
  title: { absolute: "Generated Logo Showcase — unslop.site" },
  description: "Browse logos, mascots, app icons, and brand directions generated by unslop.site visitors.",
  robots: { index: false, follow: false },
};

export default function LogoGalleryPage() {
  return <LogoGallery />;
}
