import type { Metadata } from "next";
import { LogoGallery } from "./logo-gallery";

type LogoGalleryPageProps = {
  searchParams: Promise<{ page?: string | string[] }>;
};

function galleryPageNumber(value?: string | string[]) {
  const rawPage = Array.isArray(value) ? value[0] : value;
  return rawPage && /^[1-9]\d{0,5}$/.test(rawPage) ? Number(rawPage) : 1;
}

export async function generateMetadata({ searchParams }: LogoGalleryPageProps): Promise<Metadata> {
  const page = galleryPageNumber((await searchParams).page);
  const canonical = page > 1
    ? `https://unslop.site/logo/gallery?page=${page}`
    : "https://unslop.site/logo/gallery";
  const title = page > 1
    ? `Generated Logo Showcase — Page ${page} — unslop.site`
    : "Generated Logo Showcase — unslop.site";
  const description = "Browse logos, mascots, app icons, and brand directions generated by unslop.site visitors.";

  return {
    title: { absolute: title },
    description,
    alternates: { canonical },
    robots: { index: true, follow: true },
    openGraph: { title, description, type: "website", url: canonical },
  };
}

export default async function LogoGalleryPage({ searchParams }: LogoGalleryPageProps) {
  const page = galleryPageNumber((await searchParams).page);
  return <LogoGallery key={page} initialPage={page} />;
}
